hostname='localhost'
username= 'root'
password= ''
database= 'JuegoPreguntas'
url_base= 'http://localhost'

; Configuración del Correo (PHPMailer)
mail_user = "pwtpg2712@gmail.com"
mail_password = "ehrq zayo dsay wrlt"


